---
- name: Download NiFi Registry binary
  get_url:
    url: "{{ download_mirror_uri }}/nifi/{{ nifi_registry_version }}/nifi-registry-{{ nifi_registry_version }}-bin.zip"
    dest: "/tmp/nifi-registry-{{ nifi_registry_version }}-bin.zip"

- name: Unpack NiFi Registry binary
  unarchive:
    remote_src: "yes"
    src: "/tmp/nifi-registry-{{ nifi_registry_version }}-bin.zip"
    dest: "{{ nifi_registry_config_dirs.install }}/"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
    creates: "{{ nifi_registry_config_dirs.install }}/nifi-registry-{{ nifi_registry_version }}"

- name: Fix permissions
  file:
    path: "{{ nifi_registry_config_dirs.install }}/nifi-registry-{{ nifi_registry_version }}"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
    recurse: "yes"

- name: Create NiFi Registry symlink
  file:
    src: "nifi-registry-{{ nifi_registry_version }}"
    path: "{{ nifi_registry_config_dirs.home }}"
    state: "link"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
