---
- name: Check if NiFi Registry binary exists
  stat:
    path: "{{ nifi_registry_config_dirs.binaries }}/nifi-{{ nifi_registry_version }}-bin.zip"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: zip_file

- name: Download NiFi Registry binary
  get_url:
    url: "{{ download_mirror_uri }}/nifi/{{ nifi_registry_version }}/nifi-registry-{{ nifi_registry_version }}-bin.zip"
    dest: "{{ nifi_registry_config_dirs.binaries }}/nifi-registry-{{ nifi_registry_version }}-bin.zip"
  when: not zip_file.stat.exists

- name: Unpack NiFi Registry binary
  unarchive:
    remote_src: "yes"
    src: "{{ nifi_registry_config_dirs.binaries }}/nifi-registry-{{ nifi_registry_version }}-bin.zip"
    dest: "{{ nifi_registry_config_dirs.install }}/"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
    creates: "{{ nifi_registry_config_dirs.install }}/nifi-registry-{{ nifi_registry_version }}"

- name: Fix permissions
  file:
    path: "{{ nifi_registry_config_dirs.install }}/nifi-registry-{{ nifi_registry_version }}"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
    recurse: "yes"

- name: Create NiFi Registry symlink
  file:
    src: "nifi-registry-{{ nifi_registry_version }}"
    path: "{{ nifi_registry_config_dirs.home }}"
    state: "link"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
