---
- name: Prepare system
  import_tasks: prepare.yml

- name: Install NiFi Registry
  import_tasks: install.yml

- name: Customize NiFi Registry
  import_tasks: customize.yml

- name: Run NiFi Registry as system service
  import_tasks: run.yml
