---
- name: Copy systemd template
  template:
    src: "templates/nifi-registry.service.j2"
    dest: "/etc/systemd/system/nifi-registry.service"

- name: Enable NiFi Registry service
  systemd:
    name: nifi-registry
    daemon_reload: yes
    enabled: yes
